name: itbusiness
favicon: null
layout_spectrum: 0.6041041254065931
typography_spectrum: 0.30552467750385404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3902018149383366
  lightness: 0.9187592803500593
  saturation: 0.4126891295891255
  rhythmicContrast: 0.37905982974916697
purpose: []
